#ifndef TTYD_REL_LAS_H
#define TTYD_REL_LAS_H

#include "ttyd/evtmgr.h"

#include <cstdint>

extern "C"
{
    EVT_DECLARE(las_last_evt_3_2);

    // las_mobj_set_ry
    // las_mobj_color_off
    // las_mobj_set_color
    // las__unresolved
    // las__epilog
    // las__prolog
    // las_make_name
    // las_make_name
    // las_toge_flag_onoff
    // las_toge_check_flag
    // las_get_toge_name
    // las_firebar_cb
    // las_coin_entry
    // las_firebar_disp
    // las_firebar_disp_evt
    // las_firebar_entry
    // las__firebar_trans
    // las__firebar_rot
    // las__firebar_hitCheck2
    // las__firebar_hitCheck
    // las_make_name
    // las_party_hit
    // las_chk_mario_ctrloff
    // las_party_land_on
    // las_mario_land_on
    // las_set_party_y_pos
    // las_get_party_y_pos
    // las_set_mario_y_pos
    // las_get_mario_y_pos
    // las_senkaronGetMarioPushedFlag
    // las_senkaronAttackStart
    // las_senkaronFlagOffMesPushing
    // las_senkaronFlagOnMesPushing
    // las_senkaronToEscape
    // las_senkaron_ext_shadow_disp
    // las_senkaron_ext_disp
    // las_senkaron_ext_dispent
    // las_senkaron_ext_main
    // las_party_hit_check
    // las_calc_area
    // las_move_check
    // las_senkaron_ext_init
    // las_randf
    // las_kurokaron_move_position
    // las__kurokaron_next_move_index
    // las_kurokaron_move2
    // las__kurokaron_run_away
    // las_kurokaron_get_move_pos
    // las_kurokaron_flag_check
    // las_make_name
    // las_mugen_kairou_get_list
    // las_hi_onoff
    // las_eff_guruguru
    // las_make_kagi_tbl
    // las_check_party_pos
    // las_temae_kesu
    // las_small_star
    // las_evt_las_cloud_ent
    // las_evt_las_cloud_init
    // las_evt_cloud_main
    // las__mapclsofs_all
    // las__mapsetofs_all
    // las__get_boundingbox
    // las__img_alloc_capture
    // las_get_mobj_seq
    // las_switch_alpha_off
    // las_switch_set_alpha
    // las_get_hosi_name
    // las_set_mobj_y_position
    // las_set_party_y_pos
    // las_bonbaba_wait_landon
    // las_make_name
    // las_make_name
    // las_eff_guruguru
    // las_syuryo_baria_recalc_pos
    // las_syuryo_baria
    // las_mist_add_vy
    // las_make_mist_name
    // las_eff_b_peach_mist
    // las_eff_b_peach_ripple
    // las_slowturnoff_check
    // las_make_koe_pos
    // las_make_koe_label
    // las_starstone_set_ry
    // las_starstone_set_pos
    // las_starstone_entry
    // las_pcharge_set_pos
    // las_pcharge_entry
    // las_radiation_set_pos
    // las_radiation_entry
    // las_add_vy
    // las_b_peach_msgcb
    // las_b_peach_thunder
    // las_all_hikari_onoff
    // las_map_color_tev
    // las_all_hikari_change_kuro
    // las_hikari_onoff
    // las_hikari_se
    // las_hikari_change
    // las_hikari_set_scale
    // las_rou_hikari_front_onoff
    // las_rousoku_init
    // las__hikariEntry
    // las_check_battle_end
    // las__gear_rotate
    // las__disp_icon
    // las__icon_jump_icon
    // las_party_cannot_use_command
    // las_mario_cannot_use_command
    // las_eff_magic_support
    // las_eff_magic_get_posX
    // las_eff_magic
    // las_eff_staff
    // las__krb_get_dir
    // las_vivian_comeback
    // las_eff_scanning
    // las_queen_hand_small_1000hand_set_offset_evt
    // las_queen_hand_small_1000hand_2_evt
    // las_queen_hand_small_1000hand_1_evt
    // las_queen_hand_small_drag_1_evt
    // las_queen_hand_small_drag_2_evt
    // las_queen_hand_small_drag_3_evt
    // las_queen_hand_small_drag_4_evt
    // las_queen_hand_small_dead_evt
    // las_queen_hand_small_entry_evt
    // las_slot_init
    // las_peach_shock_evt
    // las_queen_hp_drain_5_evt
    // las_queen_hp_drain_4_evt
    // las_queen_hp_drain_3_evt
    // las_queen_hp_drain_2_evt
    // las_queen_hp_drain_1_evt
    // las_queen_get_aud_num
    // las_queen_kankyaku_delete_evt
    // las_peach_hand1000_dark_drag_1_evt
    // las_eff_queen_set_alpha_evt
    // las_queen_drain
    // las_queen_thunder
    // las_change_pose
    // las_hand_main
    // las_hand_draw
    // las_hand_init
    // las_pose_main
    // las_pose_init
    // las_make_pattern
    // las_peach_talk_synchro_shadow_head_evt
    // las_shadow_queen_connect
    // las_honenoko_copy_status
    // las_honenoko_copy_status
    // las_make_name
    // las_battenSatelliteToOutside
    // las_battenSatelliteToInside
    // las_battenSatelliteTo_Main
    // las_battenSatelliteTo_Init
    // las__light_point_callback
    // las__set_draw_callback
    // las_btl_hitoffsetx
    // las_pose_check_evt_stop
    // las_pose_check_evt_run
    // las_datastrcopy
    // las_enzan_lw_load2
    // las_enzan_lw_save2
    // las_enzan_lw_load
    // las_enzan_lw_save
    // las_btlevtcmd_AnimeGetPose
    // las_battleGetBattenSatelliteInitPos
    // las_check_satellite
    // las_eff_staff
    // las_evt_eff_firechange00
    // las_evt_eff_barriersizechange
    // las_evt_eff_colorchange00
    // las_evt_eff_pokopi_thunder
    // las_bts_x_flag_wait
    // las_bts_x_flag_get
    // las_bts_x_flag_add
    // las_bts_x_flag_set
    // las_bts_wariai_enzan_0f
    // las_bts_wariai_enzan_0
    // las_bts_wariai_enzan_1f_intpl_w
    // las_bts_wariai_enzan_1f_intpl
    // las_bts_wariai_enzan_1f
    // las_bts_wariai_enzan_1
    // las__leg_smoke_effect
    // las_killer_get_angle
    // las_killer_copy_status
    // las_eff_magic_get_posX
    // las_eff_magic
    // las_mahorn_copy_status
    // las_mahorn_shuffle
    // las_mahorn_get_bunsin
    // las_set_hand_dest
    // las_hand_ctrl
    // las_hand_end
    // las_hand_init
    // las_mahorn_get_live_num
    // las_chain_main
    // las_chain_init
    // las_evt_shuryolight_delete
    // las_evt_shuryolight_run_tue_evt
    // las_evt_shuryolight_run_head_evt
    // las_evt_shuryolight_run_power_evt
    // las_evt_shuryolight_run_evt
    // las_evt_shuryolight_get_status
    // las_evt_shuryolight_get_anim_time
    // las_evt_shuryolight_wait_anim_end
    // las_evt_shuryolight_set_anim
    // las_evt_shuryolight_init
    // las_shuryolightRunEvt
    // las_shuryolightSetAnim
    // las_shuryolight_callback
    // las_eff_all_fire
    // las_eff_fire
    // las_bubble_copy_status
    // las__fire_point_callback
    // las__set_draw_callback
    // las_honenoko_copy_status
    // las_honenoko_copy_status
    // las_majo3_sort
}

#endif
