#ifndef TTYD_REL_MRI_H
#define TTYD_REL_MRI_H

#include "ttyd/evtmgr.h"

#include <cstdint>

extern "C"
{
    EVT_DECLARE(mri_minnnanokoe_evt);

    // mri__prolog
    // mri__epilog
    // mri__unresolved
    // mri_evt_mri_door_naname_func
    // mri_hakari_color
    // mri_evt_mri_get16bitdata
    // mri_mri_npc_buruburu
    // mri_toge_searchParent
    // mri_togeModeParent
    // mri_togeMoveParent
    // mri_puniModeWinjump
    // mri_togeMakeRetsu
    // mri_evt_mri_toge_make_retsu
    // mri_evt_mri_toge_retsu_stop
    // mri_evt_mri_toge_enter_init
    // mri_evt_mri_puni_win_init
    // mri_evt_mri_puni_win_attack
    // mri_evt_mri_puni_win_end
    // mri__img_alloc_capture
    // mri__ofs_get_boundingbox
    // mri__mapsetofs_all
    // mri__mapclsofs_all
    // mri_evt_cloud_main
    // mri_evt_mri_cloud_init
    // mri_evt_mri_cloud_ent
    // mri_yami_view
    // mri_anim_tevcallback
    // mri_get_puni_pos
    // mri_starstone_entry
    // mri_starstone_set_pos
    // mri_starstone_set_ry
    // mri_sysflag
    // mri_evtflash
    // mri_elder_talk_sub_punicheck
    // mri_elder_talk_sub_fadeoff
    // mri_bossrobot_batu
    // mri_bossrobot
    // mri_evt_countdown_stop
    // mri_akari_charge_entry
    // mri_mri_stg3_012_cb
    // mri_moveSwitch
    // mri_getMri02Yuka
    // mri_setPuniWeight
    // mri_getSwitch
    // mri_alpha_tev
    // mri_alpha_init_func
    // mri_alpha_set_func
    // mri_puniModeEventparent
    // mri_puni_parent
    // mri_puni_away
    // mri_evt_chuchu_back_loop
    // mri_mario_shabon_init
    // mri_mario_shabon_eff
    // mri_mario_shabon_effpos
    // mri_mario_shabon_effdel
    // mri_evt_pcharge_pos
    // mri_toge_enter_func00
    // mri_yuka_fall_check
    // mri_evt_puni_force_pose
    // mri_evtflash
    // mri_starstone_rotate_func
    // mri_evt_npc_set_anim_localtime
    // mri_ss_check
    // mri_ss_set
    // mri_puni_get_id
    // mri_puniSinCosRet
    // mri_puniInit
    // mri_puniEntry
    // mri_puniMakeTexture
    // mri_puniReset
    // mri_puniFadeOff
    // mri_puniMain
    // mri_compare
    // mri_puniGetPosePtr
    // mri_puniGetPoseNum
    // mri_puniPoseDraw
    // mri_puniDraw
    // mri_puniLoadRenderMode
    // mri_puniLoadVertex
    // mri_puniLoadTexture
    // mri_puniGetUsedTmemSize
    // mri_puniLoadTextureExit
    // mri_puniLoadTev
    // mri_camGetRy
    // mri_puniLoadShadowVertex
    // mri_puniLoadShadowTev
    // mri_puniLoadShadowRenderMode
    // mri_puniLoadShadowMtx
    // mri_puniDrawShadow
    // mri_puniGetPunidat
    // mri_puniGetPunigp
    // mri_puniGetTex
    // mri_evt_icon_disp_func
    // mri__make_texbuf
    // mri_evt_make_texbuf
    // mri_puniAnimCount
    // mri_puniAnimationInit
    // mri_puniAnimationInit2
    // mri_puniAnimation
    // mri__chukanhosei
    // mri__areacheck
    // mri__ymode_mri_09
    // mri__ymode_mri_16_00
    // mri__ymode_mri_16_01
    // mri_puniSetYPosition
    // mri_puniMapdata_MRI_06_getidx
    // mri_puniMapdata_MRI_06_getpos
    // mri_puniMapdata_MRI_09_getidx
    // mri_puniMapdata_MRI_09_getpos
    // mri_puniMapdata_MRI_16_getidx
    // mri_puniMapdata_MRI_16_getpos
    // mri_puniMapPos2Blk
    // mri_puniMapBlk2Pos
    // mri_puniMapGetInfo
    // mri_puniMapInit
    // mri_puniMapDataSet
    // mri_puniMapFindbuff
    // mri_puniTargetSearch
    // mri_puniswGetindex
    // mri_puniswSetindex
    // mri_puniswTrapGetindex
    // mri_puniswTrapSetindex
    // mri_randf
    // mri_randi
    // mri_qrndseed
    // mri_qrnd
    // mri_puniDeleteEffect
    // mri__daime_change
    // mri_PuniDokuritsu
    // mri_PuniSakanobori
    // mri_PuniChildHagure
    // mri_searchParent
    // mri_searchMario
    // mri_puniPositionCheck
    // mri_puniPositionRecover
    // mri_puniMoveAtari
    // mri_puniMoveDecel
    // mri_puniMoveLimitedNormal
    // mri_puniMoveNormal
    // mri_puniMoveSimple
    // mri_puniMoveCustom
    // mri_puniParaAttack
    // mri_puniParaDamage
    // mri_puniParaRecover
    // mri_puniParaDangerCheck
    // mri_puniParaSelfCheck
    // mri_puniParaRecoverCheck
    // mri_puniSearchRandom
    // mri_puniSearchRandom_Mikata
    // mri_puniSearchRandom_Teki
    // mri_searchBattle
    // mri_searchMikata
    // mri_searchTeki
    // mri_searchBattleMikata
    // mri_searchBattleTeki
    // mri_puniSearch
    // mri_puniModeChangeAttack
    // mri_puniModeChangeAway
    // mri_puniModeChangeFallCheck
    // mri_puniFukki
    // mri_puniModeALLCheck
    // mri_puniModeALLEndCheck
    // mri_puniModeNormal
    // mri_puniModeParentpre
    // mri_puniModeParent
    // mri_puniModeSearch
    // mri_puniModeMass
    // mri_puniModeAwayjump
    // mri_puniModeAway_sub
    // mri_puniModeAway
    // mri_puniModeAttack
    // mri_puniModeDamage
    // mri_puniModePiyori
    // mri_puniModeEscape
    // mri_puniModeRecover
    // mri_puniModeDead
    // mri_puniModeWind_sub
    // mri_puniModeWind_kaiten
    // mri_puniModeWind
    // mri_puniModeFall
    // mri_puniModePreupdraft
    // mri_puniModeUpdraft
    // mri_puniModeWonder
    // mri_puniModeFunbari
    // mri_puniModeWater
    // mri_puniModePrehagure
    // mri_puniModeHagure
    // mri_puniModeDodai
    // mri_puniModeTrap_sub
    // mri_puniModeTrap
    // mri_puniModeEnterSubInit
    // mri_puniModeEnterSub
    // mri_puniModeEnter
    // mri_puniModeExitSubInit
    // mri_puniModeExitSub
    // mri_puniModeExit
    // mri_puniModePoint
    // mri_puniModeDokan
    // mri_puniModeCustom
    // mri_puni_puni_disp
    // mri_puni_puni_shadow_disp
    // mri_puni_puni_init
    // mri_puniOption
    // mri_puniSound
    // mri_puni_puni_main
    // mri_puni_puni_dispent
    // mri_evt_puni_mem_init
    // mri_evt_puni_init
    // mri_evt_puni_set_yuka
    // mri_evt_puni_set_hamari
    // mri_evt_puni_set_maze
    // mri_evt_puni_main
    // mri_puni_init_posy
    // mri_puni_init_para
    // mri_toge_init_para
    // mri_evt_puni_rnd_pos
    // mri_evt_puni_get_systemmode
    // mri_evt_puni_set_systemmode
    // mri_evt_puni_wait_systemmode
    // mri_evt_puni_debug_info
    // mri_evt_puni_setup
    // mri_evt_toge_setup
    // mri__puniVAtari
    // mri_puniHagurePos
    // mri_evt_puni_exit
    // mri_evt_puni_init_puni
    // mri_evt_puni_init_teki
    // mri_evt_puni_get_position
    // mri_evt_puni_set_position
    // mri_evt_puni_get_dir
    // mri_evt_puni_set_dir
    // mri_evt_puni_get_anim
    // mri_evt_puni_set_anim
    // mri_evt_puni_korokoro
    // mri_evt_puni_move_position
    // mri_evt_puni_move_position2
    // mri_evt_puni_jump_position
    // mri_evt_puni_get_mode
    // mri_evt_puni_set_mode
    // mri_evt_puni_setsudan
    // mri_evt_puni_get_flag
    // mri_evt_puni_flag_onoff
    // mri_evt_puni_dokan_onoff
    // mri_evt_puni_get_lsw_index
    // mri_evt_puni_set_lsw_index
    // mri_evt_puni_get_trap_index
    // mri_evt_puni_set_trap_index
    // mri_evt_puni_set_ymode
    // mri_evt_puni_all_fall_check
    // mri_evt_puni_all_movestop
    // mri_evt_puni_count
    // mri_evt_puni_count_area
    // mri_evt_puni_zenmetsu_check
    // mri_evt_puni_landon_check
    // mri_evt_puni_pera_onoff
    // mri_evt_puni_fade_onoff
    // mri_evt_puni_attack_on
    // mri_evt_puni_puninum_onoff
    // mri_evt_puni_puninum_alpha
    // mri_evt_puni_winddisable_onoff
    // mri_evt_puni_force_se_off
    // mri_evt_puni_all_save
    // mri_evt_target_flag_onoff
    // mri_evt_target_set_position
    // mri_evt_target_set_soko
    // mri_npcGetTribeName
    // mri_puni_piders_check_func
    // mri_puni_disp_info_kassencheck
    // mri_puniCountDisp
    // mri_puni_disp_info_sub
    // mri_krb_get_dir
    // mri_waku_main
    // mri_arm_check
    // mri_eff_dead
    // mri_eff_dead_delete
    // mri_eff_hokori
    // mri_arm_init
    // mri_arm_init2
    // mri_arm_main
    // mri_arm_end
    // mri_barriern_zanzou
    // mri_barriern_zanzou2
    // mri_barriern_zanzou3
    // mri_barriern_zanzou_sub
    // mri_barriern_satellite_zanzou
    // mri_barriern_satellite_zanzou2
    // mri_barriern_satellite_zanzou_sub
    // mri_barriernSatelliteTo_Init
    // mri_barriernSatelliteTo_Main
    // mri_barriernSatelliteToInside
    // mri_barriernSatelliteToOutside
    // mri_outSplineTableSet
    // mri_outSplineTableSet_Sub
    // mri_barriern_wawawa_set_target
    // mri_barriern_wawawa_get_target
    // mri_barriern_wawawa_get_next_target
    // mri__check_satellite
    // mri_battleGetBarriernSatelliteInitPos
    // mri_piders_yarn_init
    // mri_piders_draw_yarn_sub
    // mri_piders_draw_yarn
    // mri_piders_get_num
    // mri_piders_get_zyun
    // mri_piders_get_first_pos_attr
    // mri_piders_renzoku_attack_set_target
    // mri_piders_get_target
    // mri_piders_get_next_target
    // mri_battleGetBarriernSatelliteInitPos
    // mri_eff_poison_breath
    // mri_eff_poison_barrier
    // mri_pakkun_ceil_exist
    // mri_shadow_scale_memory
    // mri_shadow_scale_small
    // mri_shadow_scale_return
    // mri_set_depthPlaneOffset
    // mri_pakkun_ceil_exist
    // mri_shadow_scale_memory
    // mri_shadow_scale_small
    // mri_shadow_scale_return
    // mri_lect_mario_ido_sub
    // mri_lect_mario_ido_sum
    // mri_lect_status_off
    // mri_lect_status_on
    // mri_x_flag_set
    // mri_x_flag_add
    // mri_x_flag_get
    // mri_x_flag_wait
    // mri_lecture_button_disp
    // mri_lecture_button_rtn
    // mri_lecture_button_set_icon_id
    // mri_lecture_button_set_alpha
    // mri_lecture_button_flag_on_off
    // mri_lecture_button_set_seq
    // mri_lecture_button_get_icon_id
    // mri_lecture_button_seq_wait
    // mri_lecture_button_set_pos
    // mri_lect_map_cam_chg_sub
    // mri_lect_map_cam_chg
    // mri_effitemgetchange_cam
    // mri_effitemgetchange_cam_ptr
    // mri_effitemget_open
    // mri_effitemget_open_ptr
    // mri_effitemget_busaiku
    // mri_lect_mobj_hit_nasi
    // mri_juyoitem_get_no
    // mri_juyoitem_end
    // mri_juyoitem_gogo
    // mri_juyoitem_goato
    // mri_lect_mobj_set_nosysblend
    // mri_lect_push_a_check
    // mri_lect_push_b_check
    // mri_bgm_start_wait
}

#endif
