#ifndef TTYD_REL_TOU2_H
#define TTYD_REL_TOU2_H

#include "ttyd/rel/tou.h"

#include <cstdint>

extern "C"
{
    extern RankingData *tou2_rank_wp;

    // tou2_gans_white_off
    // tou2_gans_white_on
    // tou2_callback
    // tou2_eff_pos
    // tou2_evt_boss_stone_r
    // tou2_starstone_sound_onoff
    // tou2_getY
    // tou2_item_jump
    // tou2_cosf
    // tou2_sinf
    // tou2_confupose
    // tou2_snd_sfx_stop
    // tou2_burst_chain
    // tou2_tribe_chk
    // tou2_screen_tev
    // tou2_GXSetTexCoordGen
    // tou2_screen_evt
    // tou2_screen_init
    // tou2_screen_capture
    // tou2_ext_kyaku_dispent
    // tou2_ext_kyaku_main
    // tou2_kyaku_disp
    // tou2_ext_kyaku_init
    // tou2_randf
    // tou2___tou_rand
    // tou2___tou_srand
    // tou2_pose_change
    // tou2_pose_main
    // tou2_pose_init
    // tou2__firstattack_setting
    // tou2_x_flag_wait
    // tou2_x_flag_get
    // tou2_x_flag_add
    // tou2_x_flag_set
    // tou2_wariai_enzan_0f
    // tou2_wariai_enzan_0
    // tou2_wariai_enzan_1f_intpl_w
    // tou2_wariai_enzan_1f_intpl
    // tou2_wariai_enzan_1f
    // tou2_wariai_enzan_1
    // tou2_check_ceil
    // tou2_down_ceil
    // tou2_init_ceil
    // tou2_ceil_exist
    // tou2_tou_champion_belt_onoff
    // tou2_tou_champion_belt
    // tou2_camGetRy
    // tou2_atan2f
    // tou2_evt_tou_print_ranking
    // tou2_disp_proc
    // tou2_printRanking
    // tou2_evt_tou_set_rule_result
    // tou2_evt_tou_set_ranking_win_lose
    // tou2_evt_tou_get_rule_msg2
    // tou2_evt_tou_get_rule_info
    // tou2_evt_tou_get_fighter_tribe
    // tou2_evt_tou_get_fighter_num
    // tou2_evt_tou_get_fighter_battle_msg
    // tou2_evt_tou_get_fighter_rank
    // tou2_evt_tou_get_fighter_name2
    // tou2_evt_tou_get_fighter_info
    // tou2_evt_tou_get_next_match
    // tou2_evt_tou_get_ranking
    void tou2_rankingControll();
    // tou2_insert
    // tou2_evt_rankingReInit
    // tou2_rankingExit
    // tou2_rankingInit
    // tou2__unresolved
    // tou2__epilog
    // tou2__prolog
    // tou2__steal_item
    // tou2_fire_bros_get_next_target
    // tou2_fire_bros_get_target
    // tou2_fire_bros_nagemakuri_set_target
    // tou2_chorobon_copy_status
    // tou2_hammer_bros_get_next_target
    // tou2_hammer_bros_get_target
    // tou2_hammer_bros_nagemakuri_set_target
    // tou2_honenoko_copy_status
    // tou2_yoshi_exist
    // tou2_get_id
    // tou2_yoshi_exist
    // tou2_get_id
    // tou2_togezo_copy_status
    // tou2_krb_get_dir
    // tou2_piders_get_next_target
    // tou2_piders_get_target
    // tou2_piders_renzoku_attack_set_target
    // tou2_piders_get_first_pos_attr
    // tou2_piders_get_zyun
    // tou2_piders_get_num
    // tou2_piders_draw_yarn
    // tou2_piders_draw_yarn_sub
    // tou2_GXEnd
    // tou2_GXPosition3f32
    // tou2_piders_yarn_init
    // tou2_eff_aura
    // tou2_eff_aura
    // tou2_eff_magic_get_posX
    // tou2_eff_magic
    // tou2_eff_staff2
    // tou2_eff_staff1
    // tou2_kamec_copy_status
    // tou2_kamec_shuffle
    // tou2_kamec_get_bunsin
    // tou2_kamec_get_live_num
    // tou2_eff_magic_get_posX
    // tou2_eff_magic
    // tou2_eff_staff2
    // tou2_eff_staff1
    // tou2_kamec_copy_status
    // tou2_kamec_shuffle
    // tou2_kamec_get_bunsin
    // tou2_kamec_get_live_num
    // tou2_eff_magic_get_posX
    // tou2_eff_magic
    // tou2_eff_staff2
    // tou2_eff_staff1
    // tou2_kamec_copy_status
    // tou2_kamec_shuffle
    // tou2_kamec_get_bunsin
    // tou2_kamec_get_live_num
    // tou2_togenoko_getnum
    // tou2_chain_main
    // tou2_chain_init
    // tou2_togezo_copy_status
    // tou2_replace_evt
    // tou2_replace_callback
    // tou2_replace_disp
    // tou2_tanf
    // tou2__disp_icon
    // tou2__icon_jump_icon
    // tou2_party_cannot_use_command
    // tou2_mario_cannot_use_command
    // tou2__steal_item
    // tou2_shadow_scale_return
    // tou2_shadow_scale_small
    // tou2_shadow_scale_memory
    // tou2_pakkun_ceil_exist
}

#endif
