#include "menus/battles.h"
#include "ttyd/battle_unit.h"

#include <cstdint>

const char *gBattleActors[TOTAL_BATTLE_UNIT_TYPES] = {
    "Goomba",
    "Paragoomba",
    "Spiky Goomba",
    "Spinia",
    "Spania",
    "Lord Crump - Prologue",
    "Gus",
    "Blooper",
    "Left Tentacle",
    "Right Tentacle",
    "Koopatrol",
    "Magikoopa",
    "Magikoopa Clone",
    "Koopa Troopa",
    "Paratroopa",
    "Fuzzy",
    "Dull Bones",
    "Bald Cleft",
    "Bristle",
    "Gold Fuzzy",
    "Fuzzy Horde",
    "Red Bones",
    "Hooktail",
    "Dark Puff",
    "Pale Piranha",
    "Cleft",
    "Pider",
    "X-Naut",
    "Yux",
    "Mini-Yux",
    "Beldam - Ch2",
    "Marilyn - Ch2",
    "Vivian - Ch2",
    "Magnus",
    "X-Fist",
    "Goomba - Glitzville",
    "KP Koopa",
    "KP Paratroopa",
    "Pokey",
    "Lakitu",
    "Spiny",
    "Hyper Bald Cleft",
    "Bob_omb",
    "Bandit",
    "Big Bandit",
    "Red Spiky Buzzy",
    "Shady Koopa",
    "Shady Paratroopa",
    "Red Magikoopa",
    "Red Magikoopa Clone",
    "White Magikoopa",
    "White Magikoopa Clone",
    "Green Magikoopa",
    "Green Magikoopa Clone",
    "Dark Craw",
    "Hammer Bro",
    "Boomerang Bro",
    "Fire Bro",
    "Red Chomp",
    "Dark Koopatrol",
    "Iron Cleft - Red",
    "Iron Cleft - Green",
    "Bowser - Ch3",
    "Rawk Hawk",
    "Macho Grubba",
    "Hyper Goomba",
    "Hyper Paragoomba",
    "Hyper Spiky Goomba",
    "Crazee Dayzee",
    "Amazy Dayzee",
    "Hyper Cleft",
    "Buzzy Beetle",
    "Spike Top",
    "Swooper",
    "Boo",
    "Atomic Boo",
    "Doopliss - Ch4 - Fight 1",
    "Doopliss - Ch4 - Invincible",
    "Doopliss - Ch4 - Fight 2",
    "Goombella - Ch4",
    "Koops - Ch4",
    "Yoshi - Ch4",
    "Flurrie - Ch4",
    "Ember",
    "Lava Bubble",
    "Green Fuzzy",
    "Flower Fuzzy",
    "Putrid Piranha",
    "Parabuzzy",
    "Bill Blaster",
    "Bullet Bill",
    "Bulky Bob_omb",
    "Cortez",
    "Cortez - Bone Pile?",
    "Hook",
    "Rapier",
    "Sword",
    "Sabre",
    "Lord Crump - Ch5",
    "X-Nauts - Stack",
    "X-Nauts - Ceiling",
    "X-Nauts - Crowd",
    "Ruff Puff",
    "Poison Pokey",
    "Spiky Parabuzzy",
    "Dark Boo",
    "Smorg",
    "Miasma - Leftmost",
    "Miasma - Topmost",
    "Miasma - Rightmost",
    "Miasma - Claw",
    "Ice Puff",
    "Frost Piranha",
    "Moon Cleft",
    "Z-Yux",
    "Mini-Z-Yux",
    "X-Yux",
    "Mini-X-Yux",
    "X-Naut PhD",
    "Elite X-Naut",
    "Magnus 2.0",
    "X-Punch",
    "Swoopula",
    "Phantom Ember",
    "Bombshell Bill Blaster",
    "Bombshell Bill",
    "Chain Chomp",
    "Dark Wizzerd",
    "Dark Wizzerd Clone",
    "Dry Bones",
    "Dark Bones",
    "Gloomtail",
    "Beldam Ch8",
    "Marilyn Ch8",
    "Doopliss - Ch8",
    "Doopliss - Ch8 - Mario",
    "Doopliss - Ch8 - Goombella",
    "Doopliss - Ch8 - Koops",
    "Doopliss - Ch8 - Yoshi",
    "Doopliss - Ch8 - Flurrie",
    "Doopliss - Ch8 - Vivian",
    "Doopliss - Ch8 - Bobbery",
    "Doopliss - Ch8 - Ms. Mowz",
    "Bowser - Ch8",
    "Kammy Koopa",
    "Grodus",
    "Grodus X",
    "Shadow Queen - Phase 1",
    "Shadow Queen - Invincible",
    "Shadow Queen - Phase 2",
    "Hand",
    "Dead Hands",
    "Gloomba",
    "Paragloomba",
    "Spiky Gloomba",
    "Dark Koopa",
    "Dark Paratroopa",
    "Badge Bandit",
    "Dark Lakitu",
    "Sky Blue Spiny",
    "Wizzerd",
    "Piranha Plant",
    "Spunia",
    "Arantula",
    "Dark Bristle",
    "Poison Puff",
    "Swampire",
    "Bob_ulk",
    "Elite Wizzerd",
    "Elite Wizzerd Clone",
    "Bonetail",
    "Unused - Red Buzzy",
    "Unused - Red Parabuzzy",
    "Unused - Red Spiky Parabuzzy",
    "Unused - Hyper Bob_omb",
    "Unused - Ultra Bob_omb",
    "Goombella - Action Commands Tutorial",
    "Frankly - Action Commands Tutorial",
    "Frankly - Special Moves Tutorial",
    "Frankly - Goomba Trio Fight",
    "Doopliss - Epilogue - Mario",
    "Flurrie - Epilogue",
    "Boo - Epilogue",
    "Atomic Boo - Epilogue",
    "Male Toad",
    "Female Toad",
    "Unused - Test",
    "Unused - Kanbu 2",
    "Unused - Beldam 2",
    "Unused - Marilyn 2",
    "Unused - Vivian 2",
    "Unused - Beldam 3",
    "Unused - Marilyn 3",
    "Unused - Mecha Kuri",
    "Unused - Mecha Kame",
    "Unused - Okorl",
    "Unused - Yowarl",
    "Unused - Tuyonarl",
    "Unused - Wanawana",
    "Unused - Minarai Kamec",
    "Unused - Shy Guy",
    "Unused - Groove Guy",
    "Unused - Pyro Guy",
    "Unused - Spy Guy",
    "Unused - Anti Guy",
    "Unused - Bzzap",
    "Unused - Mini Bzzap",
    "Unused - UFO",
    "Unused - Pennington",
    "Unused - Fighter",
    "Unused - Zess T.",
    "Unused - Master",
    "Unused - Reporter",
    "Unused - Hotdog Master",
    "Unused - Flavio",
    "Unused - Tree",
    "Unused - Switch",
    "Unused - TestNPC",
    "Bomb Squad - Bomb",
    "System",
    "Goombella - Prologue - Lord Crump Fight",
    "Mario",
    "Shell Shield",
    "Goombella",
    "Koops",
    "Yoshi",
    "Flurrie",
    "Vivian",
    "Bobbery",
    "Ms. Mowz",
};
